server:
  port: 8080
  servlet:
    context-path: /dictionary
    
    
spring:
  resources:
    static-locations: classpath:/
  

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 1MB
      max-file-size: 100MB
      max-request-size: 100MB



  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/ai
    username: root
    password: 1234


  mail:
       host: smtp.gmail.com
       port: 587
       username: koreanculturedictionary@gmail.com
       password: wasd123#
       protocol: smtp
       tls: true
       properties.mail.smtp:
           auth: true
           starttls.enable: true
           ssl.trust: smtp.gmail.com
    